spring.application.name=kitafuru

spring.datasource.url=jdbc:postgresql://localhost:5432/kitafuru_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
#生産者が追加する商品の登録時に入れる画像サイズの指定
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB