-- DROP TABLE
DROP TABLE IF EXISTS product_relations;
DROP TABLE IF EXISTS recommendation_logs;
DROP TABLE IF EXISTS product_gift_tags;
DROP TABLE IF EXISTS gift_diagnosis_logs;
DROP TABLE IF EXISTS product_views;
DROP TABLE IF EXISTS favorite;
DROP TABLE IF EXISTS favorite_products;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS product_seasons;
DROP TABLE IF EXISTS products_categories;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS gift_tags;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS producers;
DROP TABLE IF EXISTS users;


-- CREATE TABLE
-- ユーザー情報
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    image VARCHAR(255),

    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    default_payment VARCHAR(20) NOT NULL DEFAULT 'CARD'
);
 
-- 生産者情報
CREATE TABLE producers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    body TEXT,
    area VARCHAR(50) NOT NULL,
    image VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    sns_link VARCHAR(255),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
-- カテゴリー情報
CREATE TABLE category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);
 
-- 季節
CREATE TABLE seasons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    start_month INTEGER NOT NULL,
    end_month INTEGER NOT NULL,
    CHECK (start_month >= 1 AND start_month <= 12),
    CHECK (end_month >= 1 AND end_month <= 12)
);
 
-- ギフトタグ
CREATE TABLE gift_tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
 
-- 商品
CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    body TEXT,
    price INTEGER NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    origin_area VARCHAR(50) NOT NULL,
    image VARCHAR(255),
    recommendation_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id INTEGER NOT NULL,
    CONSTRAINT fk_products_producer
        FOREIGN KEY (producer_id) REFERENCES producers(id),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES category(id),
    CHECK (price >= 0),
    CHECK (stock >= 0),
    CHECK (recommendation_score >= 0)
);
 
-- 商品カテゴリー
-- productsテーブルにもcategory_idがあるため冗長だが、資料に合わせて中間テーブルも作成
CREATE TABLE products_categories (
    product_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_products_categories_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_products_categories_category
        FOREIGN KEY (category_id) REFERENCES category(id)
        ON DELETE CASCADE
);
 
-- 商品と季節の紐づけ
CREATE TABLE product_seasons (
    product_id INTEGER NOT NULL,
    season_id INTEGER NOT NULL,
    PRIMARY KEY (product_id, season_id),
    CONSTRAINT fk_product_seasons_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_product_seasons_season
        FOREIGN KEY (season_id) REFERENCES seasons(id)
        ON DELETE CASCADE
);
 
-- 注文情報
CREATE TABLE orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    price INTEGER NOT NULL DEFAULT 0,
    payment_method VARCHAR(30) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'new',
    order_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CHECK (price >= 0),
    CHECK (payment_method IN (
        'credit_card',
        'bank_transfer',
        'convenience_store',
        'cash_on_delivery'
    )),
    CHECK (status IN (
        'new',
        'preparing',
        'shipped',
        'delivered',
        'cancelled'
    ))
);
 
-- 注文詳細
CREATE TABLE order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(id),
    CHECK (quantity > 0)
);
 
-- カート
CREATE TABLE cart_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_cart_items_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE,
    CHECK (quantity > 0)
);
 
-- お気に入り商品
CREATE TABLE favorite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_products_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_favorite_products_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE
);
 
-- 商品閲覧履歴
CREATE TABLE product_views (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    view_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_views_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_product_views_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE
);
 
-- ギフト診断履歴
CREATE TABLE gift_diagnosis_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    result TEXT NOT NULL,
    diagnosis_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gift_diagnosis_logs_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);
 
-- ギフトタグ紐づけ
CREATE TABLE product_gift_tags (
    product_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    PRIMARY KEY (product_id, tag_id),
    CONSTRAINT fk_product_gift_tags_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_product_gift_tags_tag
        FOREIGN KEY (tag_id) REFERENCES gift_tags(id)
        ON DELETE CASCADE
);
 
-- おすすめ表示履歴
CREATE TABLE recommendation_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recommendation_reason VARCHAR(255),
    CONSTRAINT fk_recommendation_logs_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_recommendation_logs_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE
);
 
-- 関連商品
CREATE TABLE product_relations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    related_product_id INTEGER NOT NULL,
    CONSTRAINT fk_product_relations_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_product_relations_related_product
        FOREIGN KEY (related_product_id) REFERENCES products(id)
        ON DELETE CASCADE,
    CHECK (product_id <> related_product_id)
);
